%% 4.3 The Bell Sound

%% Case 1 - fc=110 Hz; fm=220 Hz; I0=10; tau=2sec; dur=6sec; fs=11025;
%% a) Listen to sound by playing it with the soundsc function
%run bell function and create array of values

% ff = frequency vector (containing fc and fm)
ff1 = [110,220];
% Io = scale factor for modulation index
Io1 = 10;
% tau = decay parameter for A(t) and I(t)
tau1 = 2;
% dur = duration (in sec.) of the output signal
dur1 = 6;
% fsamp = sampling rate
fsamp1 = 11025;


y1 = bell(ff1,Io1,tau1,dur1,fsamp1);

%play the sound (array and sampling rate)
soundsc(y1, fsamp);

%% b) Calculate the fundamental frequency of the "note” being played. 

%%Explain how you can verify by listening that you have the correct fundamental frequency.


%% c) Describe how you can hear the frequency content changing according to I(t)

%%Plot fi(t) versus t for comparison.

%% d) Display a spectrogram of the signal

%%Describe how the frequency content changes, and how that change is related to I(t)


%%Point out the "harmonic” structure of the spectrogram, and calculate the fundamental frequency, f0

%% e) Plot the entire signal and compare it to the envelope A(t) generated by bellenv

%plot the figure
figure(1);
plot(y1);
set(gca,'FontSize',14); %set font size
title('Amplitude vs. Sample','FontSize',14); %Title
xlabel('Sample', 'FontSize',14);% X-axis Label
ylabel('Amplitude', 'FontSize',14);% Y-axis Label
drawnow; %ensure drawings are complete

%% f) Plot about 100–200 samples from the middle of the signal and explain what you see, especially the frequency variation.



%% Case 2 - fc=220 Hz; fm=440 Hz; I0=5; tau=2sec; dur=6sec; fs=11025;

%run bell function and create array of values

% ff = frequency vector (containing fc and fm)
ff2 = [220,440];
% Io = scale factor for modulation index
Io2 = 5;
% tau = decay parameter for A(t) and I(t)
tau2 = 2;
% dur = duration (in sec.) of the output signal
dur2 = 6;
% fsamp = sampling rate
fsamp2 = 11025;


y2 = bell(ff2,Io2,tau2,dur2,fsamp2);

%play the sound (array and sampling rate)
soundsc(y2, fsamp2);

%plot the figure
figure(2);
plot(y2);
set(gca,'FontSize',14); %set font size
title('Amplitude vs. Sample','FontSize',14); %Title
xlabel('Sample', 'FontSize',14);% X-axis Label
ylabel('Amplitude', 'FontSize',14);% Y-axis Label
drawnow; %ensure drawings are complete

%% Case 3 - fc=110 Hz; fm=220 Hz; I0=10; tau=12sec; dur=3sec; fs=11025;

%run bell function and create array of values

% ff = frequency vector (containing fc and fm)
ff3 = [110,220];
% Io = scale factor for modulation index
Io3 = 10;
% tau = decay parameter for A(t) and I(t)
tau3 = 12;
% dur = duration (in sec.) of the output signal
dur3 = 3;
% fsamp = sampling rate
fsamp3 = 11025;


y3 = bell(ff3,Io3,tau3,dur3,fsamp3);

%play the sound (array and sampling rate)
soundsc(y3, fsamp3);

%plot the figure
figure(3);
plot(y3);
set(gca,'FontSize',14); %set font size
title('Amplitude vs. Sample','FontSize',14); %Title
xlabel('Sample', 'FontSize',14);% X-axis Label
ylabel('Amplitude', 'FontSize',14);% Y-axis Label
drawnow; %ensure drawings are complete

%% Case 4 - fc=110 Hz; fm=220 Hz; I0=10; tau=.3sec; dur=3sec; fs=11025;

%run bell function and create array of values

% ff = frequency vector (containing fc and fm)
ff4 = [110,220];
% Io = scale factor for modulation index
Io4 = 10;
% tau = decay parameter for A(t) and I(t)
tau4 = .3;
% dur = duration (in sec.) of the output signal
dur4 = 3;
% fsamp = sampling rate
fsamp4 = 11025;


y4 = bell(ff4,Io4,tau4,dur4,fsamp4);

%play the sound (array and sampling rate)
soundsc(y4, fsamp4);

%plot the figure
figure(4);
plot(y4);
set(gca,'FontSize',14); %set font size
title('Amplitude vs. Sample','FontSize',14); %Title
xlabel('Sample', 'FontSize',14);% X-axis Label
ylabel('Amplitude', 'FontSize',14);% Y-axis Label
drawnow; %ensure drawings are complete

%% Case 5 - fc=250 Hz; fm=350 Hz; I0=5; tau=2sec; dur=5sec; fs=11025;

%run bell function and create array of values

% ff = frequency vector (containing fc and fm)
ff5 = [250,350];
% Io = scale factor for modulation index
Io5 = 5;
% tau = decay parameter for A(t) and I(t)
tau5 = 2;
% dur = duration (in sec.) of the output signal
dur5 = 5;
% fsamp = sampling rate
fsamp5 = 11025;


y5 = bell(ff5,Io5,tau5,dur5,fsamp5);

%play the sound (array and sampling rate)
soundsc(y5, fsamp5);

%plot the figure
figure(5);
plot(y5);
set(gca,'FontSize',14); %set font size
title('Amplitude vs. Sample','FontSize',14); %Title
xlabel('Sample', 'FontSize',14);% X-axis Label
ylabel('Amplitude', 'FontSize',14);% Y-axis Label
drawnow; %ensure drawings are complete

%% Case 6 - fc=250 Hz; fm=350 Hz; I0=3; tau=1sec; dur=5sec; fs=11025;

%run bell function and create array of values

% ff = frequency vector (containing fc and fm)
ff6 = [250,350];
% Io = scale factor for modulation index
Io6 = 3;
% tau = decay parameter for A(t) and I(t)
tau6 = 1;
% dur = duration (in sec.) of the output signal
dur6 = 5;
% fsamp = sampling rate
fsamp6 = 11025;


y6 = bell(ff6,Io6,tau6,dur6,fsamp6);

%play the sound (array and sampling rate)
soundsc(y6, fsamp6);

%plot the figure
figure(6);
plot(y6);
set(gca,'FontSize',14); %set font size
title('Amplitude vs. Sample','FontSize',14); %Title
xlabel('Sample', 'FontSize',14);% X-axis Label
ylabel('Amplitude', 'FontSize',14);% Y-axis Label
drawnow; %ensure drawings are complete
